### PR TITLE
run psalm over codebase.

### PR DESCRIPTION
**Pull request by DavidGoodwin**
fixes a few phpdoc things.

Shortcodes.php -> one function call had the wrong name ....

### CODE REVIEW

**Comment by mistic100** [comment]
psalm 1.1 is required for php 5.6 (please to not remove 5.6 tests)

**Comment by DavidGoodwin** [comment]
Psalm 3.0 -> it's a dev-only requirement.

In other words, it doesn't stop anyone from using PHP-Hooks from within a PHP5.6 project/environment.

**Comment by mistic100** [comment]
obviously, but the tests are failing because of it

**Comment by DavidGoodwin** [comment]
So I see - the above might fix it; although the psalm.xml file will probably not work with psalm v1.x

**Pull request merged**
