### PR TITLE
update phpunit, improve test coverage 

### PR DESCRIPTION
**Pull request by DavidGoodwin**
Update phpunit etc. Add coverage reporting. Improve code coverage.

Probably introduces a dependency on PHP 7, but older versions are EOLed now ....

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
Hmm, actually ignore this; I'll rebase onto a new copy of the upstream repo and re-submit the PR. 
I didn't notice the first 3 changesets were included.

**Comment by DavidGoodwin** [comment]
Hmm, extra changesets don't do any harm. Ignore the above closing.

**Comment by mistic100** [comment]
Please remove the outdated engines from travis config

**Comment by mistic100** [comment]
Somehow you managed to unregister this PR from travis, the build status is not visible and the last commits didn't trigger a build... but I don't mind using Github Actions, let's totally remove travis config.

Do you want to be contributor/member on the project ?

**Comment by DavidGoodwin** [comment]
> Somehow you managed to unregister this PR from travis, the build status is not visible and the last commits didn't trigger a build... but I don't mind using Github Actions, let's totally remove travis config.

Hm. GitHub actions can't do coverage/coveralls yet.


> 
> Do you want to be contributor/member on the project ?

Sure, fine by me.

**Comment by mistic100** [comment]
> Hm. GitHub actions can't do coverage/coveralls yet.

But coveralls is not configured on travis either... And actually, you can https://github.com/marketplace/actions/coveralls-github-action

> Sure, fine by me.

Done

**Comment by DavidGoodwin** [comment]
travis was having a wonky session the other day - it's possible it's just a case of the build having never been sent to travis to perform.

**Pull request merged**
